#!/bin/sh

curl --silent "https://api.github.com/repos/$1/releases/latest" | # Get latest release from GitHub API 
grep '"tag_name":' |                                              # Get tag line
sed -E 's/.*"([^"]+)".*/\1/'                                      # Pluck JSON value
